# Generated by Django 6.0.1 on 2026-01-27 15:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('logradouro', models.CharField(help_text='Rua, avenida, alameda, etc.', max_length=200)),
                ('numero', models.CharField(help_text='Número do endereço', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Apartamento, sala, bloco, etc.', max_length=100)),
                ('bairro', models.CharField(help_text='Bairro ou distrito', max_length=100)),
                ('cidade', models.CharField(help_text='Cidade', max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Estado (UF)', max_length=2)),
                ('cep', models.CharField(help_text='Código de Endereçamento Postal', max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000', regex='^\\d{5}-?\\d{3}$')])),
                ('referencia', models.CharField(blank=True, help_text='Ponto de referência próximo', max_length=200)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'indexes': [models.Index(fields=['cidade', 'estado'], name='profissiona_cidade_0c866f_idx'), models.Index(fields=['cep'], name='profissiona_cep_9ae38c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('nome_social', models.CharField(help_text='Nome pelo qual o profissional prefere ser chamado', max_length=150)),
                ('nome_registro', models.CharField(blank=True, help_text='Nome civil/registro (opcional, para documentos)', max_length=150)),
                ('profissao', models.CharField(choices=[('MEDICO', 'Médico(a)'), ('ENFERMEIRO', 'Enfermeiro(a)'), ('PSICOLOGO', 'Psicólogo(a)'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('NUTRICIONISTA', 'Nutricionista'), ('DENTISTA', 'Dentista'), ('FONOAUDIOLOGO', 'Fonoaudiólogo(a)'), ('TERAPEUTA_OCUPACIONAL', 'Terapeuta Ocupacional'), ('FARMACEUTICO', 'Farmacêutico(a)'), ('ASSISTENTE_SOCIAL', 'Assistente Social'), ('OUTRO', 'Outro')], help_text='Área de atuação profissional', max_length=30)),
                ('registro_profissional', models.CharField(blank=True, help_text='CRM, CRE, CRP, etc.', max_length=50)),
                ('especialidade', models.CharField(blank=True, help_text='Especialização ou área específica', max_length=100)),
                ('email', models.EmailField(help_text='Email profissional', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(help_text='Telefone com DDD', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (11) 99999-9999 ou (11) 9999-9999', regex='^\\(?[1-9]{2}\\)?\\s?9?[0-9]{4}-?[0-9]{4}$')])),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp (opcional)', max_length=20, validators=[django.core.validators.RegexValidator(message='WhatsApp deve estar no formato (11) 99999-9999', regex='^\\(?[1-9]{2}\\)?\\s?9?[0-9]{4}-?[0-9]{4}$')])),
                ('biografia', models.TextField(blank=True, help_text='Breve descrição profissional', max_length=1000)),
                ('aceita_convenio', models.BooleanField(default=False, help_text='Aceita convênios médicos')),
                ('valor_consulta', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da consulta particular', max_digits=8, null=True)),
                ('endereco', models.ForeignKey(help_text='Endereço de atendimento', on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='profissionais.endereco')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'indexes': [models.Index(fields=['profissao'], name='profissiona_profiss_e95b05_idx'), models.Index(fields=['nome_social'], name='profissiona_nome_so_2e926f_idx'), models.Index(fields=['email'], name='profissiona_email_69c769_idx')],
            },
        ),
    ]
