# Generated by Django 6.0.1 on 2026-01-27 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo')),
                ('data_hora', models.DateTimeField(help_text='Data e hora agendada para a consulta')),
                ('duracao_estimada', models.PositiveIntegerField(default=60, help_text='Duração estimada em minutos')),
                ('data_hora_fim', models.DateTimeField(blank=True, help_text='Data e hora de término (calculada ou real)', null=True)),
                ('tipo_consulta', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('TELECONSULTA', 'Teleconsulta'), ('RETORNO', 'Retorno'), ('PRIMEIRA_CONSULTA', 'Primeira Consulta'), ('URGENCIA', 'Urgência')], default='PRIMEIRA_CONSULTA', help_text='Tipo da consulta', max_length=20)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('NAO_COMPARECEU', 'Não Compareceu'), ('REMARCADA', 'Remarcada')], default='AGENDADA', help_text='Status atual da consulta', max_length=20)),
                ('nome_paciente', models.CharField(help_text='Nome do paciente', max_length=150)),
                ('telefone_paciente', models.CharField(help_text='Telefone do paciente', max_length=20)),
                ('email_paciente', models.EmailField(blank=True, help_text='Email do paciente (opcional)', max_length=254)),
                ('motivo_consulta', models.TextField(blank=True, help_text='Motivo principal da consulta', max_length=500)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', max_length=1000)),
                ('observacoes_internas', models.TextField(blank=True, help_text='Observações internas (não visíveis ao paciente)', max_length=1000)),
                ('valor_consulta', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado pela consulta', max_digits=8, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('PIX', 'PIX'), ('CONVENIO', 'Convênio'), ('TRANSFERENCIA', 'Transferência')], help_text='Forma de pagamento', max_length=50)),
                ('pago', models.BooleanField(default=False, help_text='Consulta foi paga')),
                ('motivo_cancelamento', models.TextField(blank=True, help_text='Motivo do cancelamento (se aplicável)', max_length=500)),
                ('cancelado_por', models.CharField(blank=True, choices=[('PACIENTE', 'Paciente'), ('PROFISSIONAL', 'Profissional'), ('SISTEMA', 'Sistema')], help_text='Quem cancelou a consulta', max_length=20)),
                ('data_cancelamento', models.DateTimeField(blank=True, help_text='Data e hora do cancelamento', null=True)),
                ('consulta_origem', models.ForeignKey(blank=True, help_text='Consulta original (para remarques)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_remarcadas', to='consultas.consulta')),
                ('profissional', models.ForeignKey(help_text='Profissional responsável pela consulta', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'indexes': [models.Index(fields=['data_hora'], name='consultas_c_data_ho_20c880_idx'), models.Index(fields=['profissional', 'data_hora'], name='consultas_c_profiss_575b29_idx'), models.Index(fields=['status'], name='consultas_c_status_7e9334_idx'), models.Index(fields=['nome_paciente'], name='consultas_c_nome_pa_4f86cf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duracao_estimada__gt', 0)), name='duracao_positiva'), models.CheckConstraint(condition=models.Q(('valor_consulta__gte', 0), ('valor_consulta__isnull', True), _connector='OR'), name='valor_nao_negativo')],
            },
        ),
    ]
